Add NES light gun / zapper support
libretro/libretro-fceumm pull request #526
Opened 2022-08-23 00:58 UTC by turley

This code comes from https://github.com/DigiDwrf/libretro-fceumm-zapper-mod, with a few minor changes to formatting and variable names.

Credit goes to @DigiDwrf. I'm not great with C, so can't say I fully understand how this works, but I have confirmed that it does work with a real NES zapper + modified rom as described [here](http://neslcdmod.com).

Addresses issue #511.

2022-08-23 00:59 UTC, turley commented on src/input/neszapper.c
> +  nesZapperStrobe[w] = 0;
Is this doing anything, or could it be removed?

2022-08-23 01:03 UTC, turley commented
Note: there could be confusion between "Zapper" and "NES Zapper" controller types. I'm not sure what else to call it, but happy to change the naming if needed.

2022-08-23 01:50 UTC, LibretroAdmin commented
Hi, this PR is very welcome.

2022-08-23 01:51 UTC, LibretroAdmin commented
> Note: there could be confusion between "Zapper" and "NES Zapper" controller types. I'm not sure what else to call it, but happy to change the naming if needed.

Could you explain to us the difference between the two? The documentation could be updated then perhaps.

2022-08-23 03:13 UTC, turley commented
> > Note: there could be confusion between "Zapper" and "NES Zapper" controller types. I'm not sure what else to call it, but happy to change the naming if needed.
> 
> Could you explain to us the difference between the two? The documentation could be updated then perhaps.

As I understand it (someone correct me if I'm wrong), Zapper controllers receive XY coordinates from a mouse, touch screen, wiimote, etc and emulate the hit detection based on that coordinate relative to the white hit boxes drawn on the screen. The controller isn't sensing the hit boxes themselves, so the emulator is doing some extra work to calculate a hit or miss.

The NES Zapper is simpler and more closely resembles the original hardware: a sensor in the light gun detects the light (or darkness) of the hit box (or surrounding area) on the screen and reports a binary hit or miss. The delay introduced by LCD screens has typically prevented this from working, but roms patched with configurable timing enable it to work just as it did on original NES hardware. The hardware controller reports two binary states – (1) trigger and (2) light sensor.

With that in mind, I suppose the current "Zapper" controller might be more accurately called an "Emulated Zapper" (or similar), but I understand that renaming an existing entity has its downsides.

2022-08-23 07:31 UTC, DigiDwrf commented
awesome! thanks @turley for bringing implementation of this mod I added for this great emulator.

2022-08-23 07:35 UTC, DigiDwrf commented
I've been using this mod for my personal use. I programmed an arduino board as a joystick input, and another one inside my zapper that captures light and blinks a led inside the gun very fast (15 khz), so it tricks the gun to see any light.

2022-08-23 07:49 UTC, DigiDwrf commented
@turley @LibretroAdmin  I updated some codes on here: https://github.com/DigiDwrf/libretro-fceumm-zapper-mod-2, so mapping of the NES ZAPPER virtual device wires with libreto's lightgun support, "aux C" reads light detection.

2022-08-23 12:08 UTC, LibretroAdmin commented
OK, let me know how you guys want to proceed. You want me to merge this PR first or do we have to wait on something first?

2022-08-23 16:40 UTC, turley commented
@hizzlekizzle brings up a good point: when reading the light sensor state, there appears to be some ambiguity as to the “correct” way to handle it, as it is at least somewhat dependent on the electronic interface connecting the light gun to the PC.

In @DigiDwrf’s `libretro-fceumm-zapper-mod-2` repo, the [code](https://github.com/DigiDwrf/libretro-fceumm-zapper-mod-2/blob/main/src/input/lcdzapper.c#L34) reading the `detect` state doesn't invert it, whereas the code in `libretro-fceumm-zapper-mod` (and [currently in the PR](https://github.com/turley/libretro-fceumm/blob/bc0428ca8395331ce639b195ece84ca77c50e388/src/input/neszapper.c#L34)) does. After a little research, I found that [fceux’s implementation](https://github.com/TASEmulators/fceux/blob/master/src/input/lcdcompzapper.cpp#L38-L40) (which @DigiDwrf’s code seems to be based on) inverts it, so it’s probably “correct” as it is in the PR. The code works with my electronics based on [this schematic and arduino code](https://github.com/r57zone/Zapper-Light-Gun-PC/), but I'm going to a do a little more testing and research today to confirm this electrically. So far, I've seen that the patched roms are somewhat forgiving in this regard.

As @hizzlekizzle says, it will be important to link to a working schematic in the release notes.

2022-08-23 16:48 UTC, turley commented
Oddly enough, it looks like the `nesZapperStrobe` variable came from fceux's implementation (called `lcdCompZapperStrobe` [there](https://github.com/TASEmulators/fceux/blob/master/src/input/lcdcompzapper.cpp#L20), but I still don't see the variable being read/used anywhere. It looks like it could be removed (as noted earlier), but my experience with C is limited and maybe it's doing something I don't see.

2022-08-23 18:16 UTC, DigiDwrf commented
> @hizzlekizzle brings up a good point: when reading the light sensor state, there appears to be some ambiguity as to the “correct” way to handle it, as it is at least somewhat dependent on the electronic interface connecting the light gun to the PC.
> 
> In @DigiDwrf’s `libretro-fceumm-zapper-mod-2` repo, the [code](https://github.com/DigiDwrf/libretro-fceumm-zapper-mod-2/blob/main/src/input/lcdzapper.c#L34) reading the `detect` state doesn't invert it, whereas the code in `libretro-fceumm-zapper-mod` (and [currently in the PR](https://github.com/turley/libretro-fceumm/blob/bc0428ca8395331ce639b195ece84ca77c50e388/src/input/neszapper.c#L34)) does. After a little research, I found that [fceux’s implementation](https://github.com/TASEmulators/fceux/blob/master/src/input/lcdcompzapper.cpp#L38-L40) (which @DigiDwrf’s code seems to be based on) inverts it, so it’s probably “correct” as it is in the PR. The code works with my electronics based on [this schematic and arduino code](https://github.com/r57zone/Zapper-Light-Gun-PC/), but I'm going to a do a little more testing and research today to confirm this electrically. So far, I've seen that the patched roms are somewhat forgiving in this regard.

The reason I didn't invert the signal is because, after a lot of testing and coding on my device, there's less latency on this latter configuration. Logic anticipation is needed too (by 2 frames or so), or the detection will be just to late for the core, and won't register a "hit".

2022-08-23 18:16 UTC, turley commented on src/input/neszapper.c
> +  nesZapperStrobe[w] = 0;
Thanks @DigiDwrf. I see that the `StrobeNesZapper` function is referenced (and would leave the function there), but I'm referring to the `nesZapperStrobe` variable. Not seeing that read from anywhere.

2022-08-23 18:52 UTC, DigiDwrf commented
@turley I've been studying the way the zapper detects light, and sometimes it's not consistent, this is the reason I think the NES was designed this way, the signal stays HIGH until the gun "turns off" when it sees light from a 15kh source. This can make the state of the signal to "blink", adding latency or false negatives, even on real hardware (maybe?), if it would be LOW at first, and then sending a HIGH signal. Just some guessings here, this not has to be necessarily true, but latency decreased by ~10ms (or more) when I mimicked the real hardware behaviour.

2022-08-23 19:06 UTC, turley commented
> @turley I've been studying the way the zapper detects light, and sometimes it's not consistent, this is the reason I think the NES was designed this way, the signal stays HIGH until the gun "turns off" when it sees light from a 15kh source. This can make the state of the signal to "blink", adding latency or false negatives, even on real hardware (maybe?), if it would be LOW at first, and then sending a HIGH signal. Just some guessings here, this not has to be necessarily true, but latency decreased by ~10ms (or more) when I mimicked the real hardware behaviour.

Right, it's not a simple mapping of light = 0, dark = 1 (or even reversed). The circuit used in the light gun gives a very brief pulse when the phototransistor detects a significant *change* in light level. I've found a few blogs mention this, but I might have to break out an oscilloscope to see how exactly what it's doing. In the end, it's ultimately trying to thwart cheating in the game by just pointing toward a light, but the game itself doesn't appear to be doing that logic (if the sensor control reports always ON to the emulator, it registers every shot as a hit), so the circuit is doing that instead.

2022-08-23 19:28 UTC, DigiDwrf commented
> > @turley I've been studying the way the zapper detects light, and sometimes it's not consistent, this is the reason I think the NES was designed this way, the signal stays HIGH until the gun "turns off" when it sees light from a 15kh source. This can make the state of the signal to "blink", adding latency or false negatives, even on real hardware (maybe?), if it would be LOW at first, and then sending a HIGH signal. Just some guessings here, this not has to be necessarily true, but latency decreased by ~10ms (or more) when I mimicked the real hardware behaviour.
> 
> @DigiDwrf Right, it's not a simple mapping of light = 0, dark = 1 (or even reversed). The circuit used in the light gun gives a very brief pulse when the phototransistor detects a significant _change_ in light level. I've found a few blogs mention this, but I might have to break out an oscilloscope to see exactly what it's doing. In the end, it's ultimately trying to thwart cheating in the game by just pointing toward a light, but the game itself doesn't appear to be doing that logic (if the sensor control reports always ON to the emulator, it registers every shot as a hit), so the circuit is doing that instead.

Correct. Now, the actual harware looks for a LOW signal to register a "HIT". An unmodified rom (e.g. Duck Hunt) will look for a LOW signal in the sensor line happening **at the same time** the frame with the box is drawn on screen. Before that frame, if the signal was LOW it will record a MISS, that's the reason a full black frame is shown first. The code protects itself from cheating (pointing to the sun, or another fast blinking source of light, stuff like that). Modded roms remove this protection due to latency issues, so they will register a HIT at all times, as long as the signal is LOW (of course, it can be inverted but it adds latency with real zapper hardware).

2022-08-23 19:50 UTC, turley commented
@DigiDwrf Sounds good. I think I’ve made sense of it. The gun works best with the light sensor pin pulled HIGH. The resistor used (whether from the microcontroller’s INPUT_PULLUP, a separate resistor, or combination of the two) should to be tuned for the phototransistor and environment. [This video](https://www.youtube.com/watch?v=Yg3TomAcpX4) talks more about that. [My gun](https://www.amazon.com/dp/B000MEA9TQ) is working best with about 10 kOhm (and no pull-up configured in the microcontroller).

Anyway, I think we’re good with the code inverting the sensor state as it does currently. The microcontroller registers and reports the control state ON briefly on the transition from dark to light, and [this code])(https://github.com/turley/libretro-fceumm/blob/bc0428ca8395331ce639b195ece84ca77c50e388/src/input/neszapper.c#L34) flips it to what the game expects (OFF for the transition to light) to register a hit.

2022-08-23 19:58 UTC, hizzlekizzle commented
Will there need to be any additional core options for latency tuning, etc?

2022-08-23 20:02 UTC, turley commented
> Will there need to be any additional core options for latency tuning, etc?

I don't think so, as the patched roms have a mechanism to do that, and it wouldn't work with modern screens without a patched rom anyway. I suspect if someone is using a CRT, it may work as-is with an unmodified rom, but I can't confirm that.

2022-08-23 20:03 UTC, DigiDwrf commented
> Will there need to be any additional core options for latency tuning, etc?

I'm using automatic frame delay and run-ahead frames (between 1 and 3, it depends on the game, maybe on the hardware too)

2022-08-23 20:06 UTC, DigiDwrf commented
> 

Sure, a CRT would be the best option always. The problem with the patched roms is that there will be a noticeable delay playing the game, that's why predictive run-ahead can solve this issue

2022-08-23 20:54 UTC, turley commented on src/input/neszapper.c
> +  nesZapperStrobe[w] = 0;
After looking at some other code where the strobe is used, I'm fairly confident it's not needed or used in this case. I removed it and tested with my own light gun setup, and it still works the same.

2022-08-23 21:00 UTC, turley commented
I feel good with this being merged at this point. Should the distinction between "Zapper" and "NES Zapper" be documented somewhere in this PR, or would that be added later in the changeling along with the next release?

2022-08-23 21:01 UTC, DigiDwrf commented on src/input/neszapper.c
> +  nesZapperStrobe[w] = 0;
I'ts a uint32 array variable on line 20
```
static uint32 nesZapperStrobe[2];
```

2022-08-23 21:01 UTC, DigiDwrf commented on src/input/neszapper.c
> +  nesZapperStrobe[w] = 0;
> Thanks @DigiDwrf. I see that the `StrobeNesZapper` function is referenced (and would leave the function there), but I'm referring to the `nesZapperStrobe` variable. Not seeing that read from anywhere.

I'ts a uint32 array variable on line 20
```
static uint32 nesZapperStrobe[2];
```

2022-08-23 21:29 UTC, DigiDwrf commented
> I feel good with this being merged at this point. Should the distinction between "Zapper" and "NES Zapper" be documented somewhere in this PR, or would that be added later in the changelog along with the next release?

Maybe "Emulated Zapper" as you proposed before ;)

2022-08-24 00:33 UTC, turley commented
Added a branch in my fork with renamed zappers [here](https://github.com/turley/libretro-fceumm/commit/421b87a36eb4684c5463f38710b1871ceca7a0e3). It renames them to "Zapper (Emulated)" and "Zapper (NES)". If the project owners would prefer that naming, I can merge that into my PR.

2022-08-24 08:43 UTC, LibretroAdmin commented
> Added a branch in my fork with renamed zappers [here](https://github.com/turley/libretro-fceumm/commit/421b87a36eb4684c5463f38710b1871ceca7a0e3). It renames them to "Zapper (Emulated)" and "Zapper (NES)". If the project owners would prefer that naming, I can merge that into my PR.

Sure, go ahead.

2022-08-24 09:48 UTC, negativeExponent commented
dont make it more complicated than it already is. Leave the Zapper label alone, unless, there's an actual name or proper name for this peripheral (this Zapper label is also used on VS System).

label the new lcd zapper the same as the original but with prefix (like Zapper (LCD Compatible or something same label what fceux uses)

2022-08-24 10:05 UTC, LibretroAdmin commented
Fine then, do what @negativeExponent says and then we can finally go ahead and merge this thing.

Just give me the go-ahead sign when we are good to go.

2022-08-24 14:56 UTC, turley commented
> dont make it more complicated than it already is. Leave the Zapper label alone, unless, there's an actual name or proper name for this peripheral (this Zapper label is also used on VS System).
> 
> label the new lcd zapper the same as the original but with prefix (like Zapper (LCD Compatible or something same label what fceux uses)

To my knowledge, the most accurate name for this is "NES Zapper" (https://en.wikipedia.org/wiki/NES_Zapper). I avoided calling it "LCD Compatible" (as fceux does) because nothing about the peripheral itself or this implementation make it compatible with modern displays (patched ROMs *can* do that, but this could just as easily be used on a CRT).

So maybe the naming currently in the PR is the most accurate (in my opinion), especially if you don't want to mess with the original Zapper's name.

If you all insist on the same name used in fceux, no worries - I'll go ahead and change it.

2022-08-24 18:03 UTC, hizzlekizzle commented
I agree that "emulated" vs "physical" or "hardware" or whatever is more informative.

2022-08-24 20:41 UTC, turley commented
Hopefully this latest revision satisfies everyone.

Zapper (Emulated) = Pointing device (mouse, touchscreen, wiimote, etc)
Zapper (Hardware) = Real NES Zapper hardware (or hardware that behaves similarly)

@DigiDwrf All the schematics I've seen for such devices online appear to use the convention of reporting the sensor "button" as active only when the light change is detected (it's somewhat non-standard to have it inverted and normally ON from the USB device). This is also compatible with fceux's implementation. I have not noticed any delay with it this way (perhaps you're seeing a delay from the trigger itself, as the game doesn't register a shot until a transition from ON to OFF [i.e., when the trigger is released], but apparently the original NES Zapper has a mechanism to physically release the trigger even if it's held down, so less of an issue).

2022-08-24 21:10 UTC, DigiDwrf commented
> Hopefully this latest revision satisfies everyone.
> 
> Zapper (Emulated) = Pointing device (mouse, touchscreen, wiimote, etc) Zapper (Hardware) = Real NES Zapper hardware (or hardware that behaves similarly)
> 
> @DigiDwrf All the schematics I've seen for such devices online appear to use the convention of reporting (via the USB controller) the sensor "button" as active only when the light change is detected (it's somewhat non-standard to have it inverted and normally ON from the USB device). This is also compatible with fceux's implementation. I have not noticed any delay with it this way (perhaps you're seeing a delay from the trigger itself, as the game doesn't register a shot until a transition from ON to OFF [i.e., when the trigger is released], but apparently the original NES Zapper has a mechanism to physically release the trigger even if it's held down, so less of an issue).

Sure, I understand, and i know is not-standard. But, can we implement AUX_B for original signaling? I think it can be helpfull, and doesn't harm anyone ^^ it's a win-win!

2022-08-24 21:14 UTC, turley commented
> > Hopefully this latest revision satisfies everyone.
> > Zapper (Emulated) = Pointing device (mouse, touchscreen, wiimote, etc) Zapper (Hardware) = Real NES Zapper hardware (or hardware that behaves similarly)
> > @DigiDwrf All the schematics I've seen for such devices online appear to use the convention of reporting (via the USB controller) the sensor "button" as active only when the light change is detected (it's somewhat non-standard to have it inverted and normally ON from the USB device). This is also compatible with fceux's implementation. I have not noticed any delay with it this way (perhaps you're seeing a delay from the trigger itself, as the game doesn't register a shot until a transition from ON to OFF [i.e., when the trigger is released], but apparently the original NES Zapper has a mechanism to physically release the trigger even if it's held down, so less of an issue).
> 
> Sure, I understand, and i know is not-standard. But, can we implement AUX_B for original signaling? I think it can be helpfull, and doesn't harm anyone ^^ it's a win-win!

Sounds like a good option. I'll add a revision with that included. As far as I know, it shouldn't cause any other unintended consequences.

2022-08-24 21:18 UTC, DigiDwrf commented
![image](https://user-images.githubusercontent.com/74699493/186524720-e6817452-a0ea-4713-a1c9-9676111db1d1.png)
@turley btw, this is what happens when I don't plug my zapper into my usb device, and the signal is inverted in code, since it's not hardwired, I use a NES original port wired to the board.
![image](https://user-images.githubusercontent.com/74699493/186525503-c0867b20-b036-4bbc-b221-453d15bd4c8e.png)

2022-08-24 22:08 UTC, turley commented
@DigiDwrf Let me know if the latest revision works for you, using AUX_B.

2022-08-24 23:39 UTC, DigiDwrf commented
> @DigiDwrf Let me know if the latest revision works for you, using AUX_B.

Have you tested this code? I think we have to work some code inside libreto.c, somehing like this:
```
static const keymap lightgunmap[] = {
  { RETRO_DEVICE_ID_LIGHTGUN_TRIGGER, ZAPPER_TRIGGER },
  { RETRO_DEVICE_ID_LIGHTGUN_AUX_B, ZAPPER_DETECT },
  { RETRO_DEVICE_ID_LIGHTGUN_AUX_C, ZAPPER_DETECT_INV },
};

typedef struct {
   bool enable_4player;                /* four-score / 4-player adapter used */
   bool up_down_allowed;               /* disabled simultaneous up+down and left+right dpad combinations */

   /* turbo related */
   uint32_t turbo_enabler[MAX_PLAYERS];
   uint32_t turbo_delay;

   uint32_t type[MAX_PLAYERS + 1];     /* 4-players + famicom expansion */

   /* input data */
   uint32_t JSReturn;                  /* player input data, 1 byte per player (1-4) */
   uint32_t MouseData[MAX_PORTS][3];   /* nes mouse data */
   uint32_t LightgunData[MAX_PORTS][3];    /* nes lightgun data */
   uint32_t FamicomData[3];            /* Famicom expansion port data */
} NES_INPUT_T;

...

void get_lightgun_input(unsigned port, uint32_t* zapdata)
{
    int i = 0;
    for (i = 0; i < 3; i++)
        zapdata[i] = input_cb(port, RETRO_DEVICE_LIGHTGUN, 0, lightgunmap[i].retro);
}
```
then, inside fceu.h
```
#define ZAPPER_TRIGGER          0
#define ZAPPER_DETECT           1
#define ZAPPER_DETECT_INV       2
```

Finally, you can borrow Libreto's input into the neszapper.c code:

```
#include <string.h>
#include "share.h"

typedef struct {
  uint32 trigger;
  uint32 detect;
  uint32 detectInv;
} ZAPPER;

static ZAPPER ZD[2];

static uint8 FP_FASTAPASS(1) ReadNesZapper(int w) {
  uint8 ret = 0;
  if (ZD[w].trigger) {
    ret |= 0x10;
  if (ZD[w].detect || !ZD[w].detectInv) {
    ret |= 0x8;
  }
  return ret;
}

void FP_FASTAPASS(3) UpdateNesZapper(int w, void *data, int arg) {
  uint32* ptr = (uint32*)data;
  ZD[w].trigger = ptr[0];
  ZD[w].detect = ptr[1];
  ZD[w].detectInv = ptr[2];
}

static INPUTC NesZapperCtrl = { ReadNesZapper, 0, 0, UpdateNesZapper, 0, 0 };

INPUTC *FCEU_InitNESZapper(int w) {
  memset(&ZD[w], 0, sizeof(ZAPPER));
  return(&NesZapperCtrl);
}
```

since ret |= 0x4;  adds a value in a memory position inside the NES core, it won't work this way I think, it always will have to be 0x8, but adds a binay that comes from the input source. Let me know if I'm mistaken.

2022-08-24 23:54 UTC, turley commented
@DigiDwrf Yes, I think you're correct. As mentioned previously, I'm not great with C 😄 . I'll try to work in those changes and test.

2022-08-25 00:15 UTC, DigiDwrf commented
> @DigiDwrf Yes, I think you're correct. As mentioned previously, I'm not great with C 😄 . I'll try to work in those changes and test.

Coding can be so confusing! XD, there's a lot I don't know yet :P

2022-08-25 00:35 UTC, turley commented
@DigiDwrf Doesn't seem to be working for me. I modified my arduino code to invert how it reports the sensor pin, and tested with [this branch](https://github.com/turley/libretro-fceumm/tree/fixed-aux-b). Did I miss something in your code suggestion, or is it working for you?

2022-08-25 00:40 UTC, DigiDwrf commented
> @DigiDwrf Doesn't seem to be working for me. I modified my arduino code to invert how it reports the sensor pin, changed my retroarch config to use AUX_B, and tested with [this branch](https://github.com/turley/libretro-fceumm/tree/fixed-aux-b). Did I miss something in your code suggestion, or is it working for you?

I'm gonna test, and let you know what is missing

2022-08-25 01:07 UTC, DigiDwrf commented
> @DigiDwrf Doesn't seem to be working for me. I modified my arduino code to invert how it reports the sensor pin, changed my retroarch config to use AUX_B, and tested with [this branch](https://github.com/turley/libretro-fceumm/tree/fixed-aux-b). Did I miss something in your code suggestion, or is it working for you?

I need to know, does the AUX_C works? or none of them?

2022-08-25 01:46 UTC, DigiDwrf commented
@turley how can I build the core for windows x64 from your repository?

2022-08-25 02:46 UTC, turley commented
> I need to know, does the AUX_C works? or none of them?

AUX_C works, but AUX_B doesn't. Sorry I don't know about building on windows, but it would be the same for my fork as for the main one. I'm using linux (retropie).

2022-08-25 03:06 UTC, DigiDwrf commented
> > I need to know, does the AUX_C works? or none of them?
> 
> AUX_C works, but AUX_B doesn't. Sorry I don't know about building on windows, but it would be the same for my fork as for the main one. I'm using linux (retropie).

I discovered the problem! AUX_B works, but my code is fauly because I'm using "or", since inverted signal sends a high value from AUX_C all the time, AUX_B is never able to output a negative, it "blinds" AUX_B. I'm working in a new code, I'll post it on here ASAP ;)

2022-08-25 03:49 UTC, turley commented
> I discovered the problem! AUX_B works, but my code is fauly because I'm using "or", since inverted signal sends a high value from AUX_C all the time, AUX_B is never able to output a negative, it "blinds" AUX_B. I'm working in a new code, I'll post it on here ASAP ;)

That makes sense. Without knowing which AUX is being used, is there a way to know which value to output? It sounds like maybe it would require an additional core option (in which case it would be better to toggle whether or not to invert, using the same port), but I'm not familiar with how to do that.

2022-08-25 05:52 UTC, DigiDwrf commented
> > I discovered the problem! AUX_B works, but my code is fauly because I'm using "or", since inverted signal sends a high value from AUX_C all the time, AUX_B is never able to output a negative, it "blinds" AUX_B. I'm working in a new code, I'll post it on here ASAP ;)
> 
> That makes sense. Without knowing which AUX is being used, is there a way to know which value to output? It sounds like maybe it would require an additional core option (in which case it would be better to toggle whether or not to invert, using the same port), but I'm not familiar with how to do that.
> 
> I suppose some analysis of the value over time could auto-detect the correct behavior (the light sensor should never be active for longer than very short intervals), but that could be somewhat complicated and prone to issues.

A core option seems a better option, I found a way! I'm about to deploy a new code

2022-08-25 06:06 UTC, DigiDwrf commented
![image](https://user-images.githubusercontent.com/74699493/186586629-e6b3bcf9-ef49-49ba-bae2-c90318a457b9.png)
 
 All done! It works :D you can fetch it from here: https://github.com/DigiDwrf/libretro-fceumm-zapper-mod-2. btw, I changed the input, now it uses AUX_A, just because there's not a good reason for use AUX_C now that I think about it...

2022-08-25 12:56 UTC, hizzlekizzle commented
I like the inversion option! That'll take some of the pressure off of people making their own hardware, whether they modify an original zapper or make a from-scratch device.

> Leave the Zapper label alone, unless, there's an actual name or proper name for this peripheral

Circling back to @negativeExponent's request/suggestion, are you guys still using the NESZAPPER name internally? If so, can we change that to HWLIGHTGUN or similar? I fear the NES prefix specifically and the "ZAPPER" name in general may be confusing for contributors in the future, since it doesn't really inform us as to what this thing actually is (that is, they're *all* NES Zappers, whether HW or SW, and the HIT/MISS behavior is very different from what someone would expect from normal software emu light gun behavior).

Is there a generic name for these HIT/MISS lightguns, perhaps?

2022-08-25 18:11 UTC, turley commented
I've merged in those changes, and successfully tested it both ways (non-inverted and inverted signal behavior).

2022-08-25 18:21 UTC, DigiDwrf commented
> > Circling back to @negativeExponent's request/suggestion, are you guys still using the NESZAPPER name internally? If so, can we change that to HWLIGHTGUN or similar?
> 
> Sounds good. I'll get that changed.
> 
> > Is there a generic name for these HIT/MISS lightguns, perhaps?
> 
> That's a good question. It's tricky because one could argue that these devices are pretty much the definition of what a light gun/zapper actually is (on NES anyway), but to your point they're different from what has traditionally been implemented in emulators.
> 
> For now, I'll restore the "Zapper" label as it was, and change this new label to "Hardware Light Gun" (to match the internal HWLIGHTGUN name).

The reason I chose NESZAPPER as an internal name is because ZAPPER was already taken by mouse/touchscreen emulation, and that part of the code uses the actual name of each device: joypad, zapper, arkanoid, powerglove, etc. In theory, we could have names like this: SWZAPPER instead of ZAPPER, and HWZAPPER instead of NESZAPPER (now HWLIGHTGUN), but I think this definition HWLIGHTGUN is pretty good already, I wont mess with it anymore (Unless you think that changing all this names would be a good idea). Nice job!

2022-08-26 00:20 UTC, DigiDwrf commented
@turley I've placed the "Invert Hardware Light Gun Signal" option under Zapper tolerance on here: https://github.com/DigiDwrf/libretro-fceumm-zapper-mod-2, it's kinda inconsistent between the other two zapper options, can lead to confusions.

2022-08-26 01:38 UTC, turley commented
@DigiDwrf That crossed my mind also. I've made that change and squashed commits in the PR. Hopefully we're close to being able to get this merged.

2022-08-26 02:35 UTC, hizzlekizzle commented
alright, if you guys are happy with it, we can bring @LibretroAdmin in for a final review and merge.

2022-08-27 05:21 UTC, DigiDwrf commented
> alright, if you guys are happy with it, we can bring @LibretroAdmin in for a final review and merge.

I'm happy with it! Let's go.

2022-08-27 21:42 UTC, DigiDwrf commented
@turley What do you think about having another option to invert trigger signaling as well? Original Zapper has switch that once is fully pressed, it's released, and the NES responds to it one it goes from 1 to 0. This may help other HW that uses a "0 = lifted, 1= fully pressed" configuration.

2022-08-27 22:05 UTC, DigiDwrf commented
> > alright, if you guys are happy with it, we can bring @LibretroAdmin in for a final review and merge.
> 
> I'm happy with it! Let's go.

@hizzlekizzle sorry, I thought it was ready but not yet! Just adding a new option that could be very useful, and we're done 👍

2022-08-27 23:24 UTC, turley commented
> @turley What do you think about having another option to invert trigger signaling as well? Original Zapper has a switch that once is fully pressed, it's released, and the NES responds to it once it goes from 1 to 0. This may help other HW that uses a "0 = lifted, 1= fully pressed" configuration.

@DigiDwrf If the trigger button behaves like any other button and it's just the game itself that fires on `release` rather than on `down`, then I'd be inclined to leave it the way it is. In other words, if hardware implementations want to include a release mechanism (as the original NES zapper did) or replicate it in their firmware, that's up to them. For those that don't (my light gun doesn't), it still works fine and is hardly noticeable.

On the other hand, if the emulator is currently sending the wrong signal for the state of the physical button, then the option is probably warranted.

2022-08-27 23:49 UTC, DigiDwrf commented
> > @turley What do you think about having another option to invert trigger signaling as well? Original Zapper has a switch that once is fully pressed, it's released, and the NES responds to it once it goes from 1 to 0. This may help other HW that uses a "0 = lifted, 1= fully pressed" configuration.
> 
> @DigiDwrf If the trigger button behaves like any other button and it's just the game itself that fires on `release` rather than on `down`, then I'd be inclined to leave it the way it is. In other words, if hardware implementations want to include a release mechanism (as the original NES zapper did) or replicate it in their firmware, that's up to them. For those that don't (my light gun doesn't), it still works fine and is hardly noticeable.
> 
> On the other hand, if the emulator is currently sending the wrong signal for the state of the physical button, then the option is probably warranted.

What I mean is that the way I've coded this trigger works with original Zapper functionality, it's not inverted. Using a non-release trigger (0 = released, 1 = down), will lead the player to stop pressing to make it work, remember that the NES games do that: fire on release, so If someone creates their own hardware with a simple "ON when hold button", the will need to invert the signal so the experience will be good enough. Try using the default zapper device, you'll see that when you press the button, it shoots. Now trying using this new hardware device, you'll see that it fires on release, like the original harware would do, it would be necessary to add this option too. I'm about to finish with it 👍, will be just the same like the sensor option,

2022-08-28 00:00 UTC, turley commented
> > > @turley What do you think about having another option to invert trigger signaling as well? Original Zapper has a switch that once is fully pressed, it's released, and the NES responds to it once it goes from 1 to 0. This may help other HW that uses a "0 = lifted, 1= fully pressed" configuration.
> > 
> > 
> > @DigiDwrf If the trigger button behaves like any other button and it's just the game itself that fires on `release` rather than on `down`, then I'd be inclined to leave it the way it is. In other words, if hardware implementations want to include a release mechanism (as the original NES zapper did) or replicate it in their firmware, that's up to them. For those that don't (my light gun doesn't), it still works fine and is hardly noticeable.
> > On the other hand, if the emulator is currently sending the wrong signal for the state of the physical button, then the option is probably warranted.
> 
> What I mean is that the way I've coded this trigger works with original Zapper functionality, it's not inverted. Using a non-release trigger (0 = released, 1 = down), will lead the player to stop pressing to make it work, remember that the NES games do that: fire on release, so If someone creates their own hardware with a simple "ON when hold button", the will need to invert the signal so the experience will be good enough. Try using the default zapper device, you'll see that when you press the button, it shoots. Now trying using this new hardware device, you'll see that it fires on release, like the original harware would do, it would be necessary to add this option too. I'm about to finish with it 👍, will be just the same like the sensor option,

👍 My light gun does as you say (doesn't fire until release), but I honestly don't even notice unless specifically looking for that. That said, I'm good with adding the option to the PR, but just wanted to keep things as simple as possible 😄

2022-08-28 00:16 UTC, DigiDwrf commented
> > What I mean is that the way I've coded this trigger works with original Zapper functionality, it's not inverted. Using a non-release trigger (0 = released, 1 = down), will lead the player to stop pressing to make it work, remember that the NES games do that: fire on release, so If someone creates their own hardware with a simple "ON when hold button", the will need to invert the signal so the experience will be good enough. Try using the default zapper device, you'll see that when you press the button, it shoots. Now trying using this new hardware device, you'll see that it fires on release, like the original harware would do, it would be necessary to add this option too. I'm about to finish with it 👍, will be just the same like the sensor option,
> 
> 👍 My light gun does as you say (doesn't fire until release), but I honestly don't even notice unless specifically looking for that. That said, I'm good with adding the option to the PR, but just wanted to keep things as simple as possible 😄

Cool. So, I'm leaving this two options enabled (both inverted) by default, this way should be good enough for the way most modern devices work. The idea, as you say is, to make it as simple as posible, but also flexible with different devices.

2022-08-28 01:54 UTC, DigiDwrf commented
![image](https://user-images.githubusercontent.com/74699493/187054121-b60efe32-20d3-456a-84ad-4826023b3e85.png)

@turley @hizzlekizzle IT'S READY! `DigiDwrf/libretro-fceumm-zapper-mod-2)`
Names of variables and definitions have changed too, I think this is the way to go. Let me know what do you think 😄

2022-08-28 03:15 UTC, turley commented
Thanks @DigiDwrf - I really appreciate the code. I'll incorporate the additional core option into this PR. I'm not exactly sure who the `libretro-fceumm` maintainers are, but it sounded like I was asked earlier to leave `zapper` alone, so for now I'm planning to hold off on those changes. The`swzapper` raname (and combined implementation) could probably be a future PR, as I think that probably deserves some more discussion.

2022-08-28 04:05 UTC, DigiDwrf commented
I just understood how to use forks, I made my own fork 😃 `DigiDwrf/libretro-fceumm-lightgun-support`

2022-08-28 04:06 UTC, DigiDwrf commented
> Thanks @DigiDwrf - I really appreciate the code. I'll incorporate the additional core option into this PR. I'm not exactly sure who the `libretro-fceumm` maintainers are, but it sounded like I was asked earlier to leave `zapper` alone, so for now I'm planning to hold off on those changes. The`swzapper` raname (and combined implementation) could probably be a future PR, as I think that probably deserves some more discussion.

you're welcome! I've just understood how to use forks, I made my own fork 😃 DigiDwrf/libretro-fceumm-lightgun-support I've errased all other repositories.

2022-08-28 16:02 UTC, turley commented
This PR has been updated to include minimal changes for adding hardware light gun support, along with options for inverting signals (for different hardware implementations). I've tested to confirm it works with a real light gun, and I've left the `zapper` (label and implementation) alone as requested. I feel that it's in a state that could be merged (with review from @LibretroAdmin).

Hopefully we can get this merged, and then @DigiDwrf can submit an additional PR for changes to the original `zapper`.

2022-08-29 00:13 UTC, DigiDwrf commented
> This PR has been updated to include minimal changes for adding hardware light gun support, along with options for inverting signals (for different hardware implementations). I've tested to confirm it works with a real light gun, and I've left the `zapper` (label and implementation) alone as requested. I feel that it's in a state that could be merged (with review from @LibretroAdmin).
> 
> Hopefully we can get this merged, and then @DigiDwrf can submit an additional PR for changes to the original `zapper`.

Good! Now, theres a catch, there are definitions inside libreto.c that goes like this:

```
#define RETRO_DEVICE_AUTO           RETRO_DEVICE_JOYPAD
#define RETRO_DEVICE_GAMEPAD        RETRO_DEVICE_SUBCLASS(RETRO_DEVICE_JOYPAD, 1)
#define RETRO_DEVICE_ZAPPER         RETRO_DEVICE_SUBCLASS(RETRO_DEVICE_MOUSE,  0) // Emulated zapper with a mouse
#define RETRO_DEVICE_HWLIGHTGUN     RETRO_DEVICE_SUBCLASS(RETRO_DEVICE_LIGHTGUN, 0) //Emulated zapper with a lightgun
#define RETRO_DEVICE_ARKANOID       RETRO_DEVICE_SUBCLASS(RETRO_DEVICE_MOUSE,  1)
```
The problem is that this are not physical devices (joypad, mouse, etc.), this are emulated NES devices' names, and a "Hardware Light Gun" for the NES/FC doesn't exist. So, for now, we could leave ZAPPER as it is, but HWLIGHTGUN will lead to more confusion. I really think that we have to give it a name that references the Zapper device, we could use HWZAPPER, ZAPPER_B, or any other option that would mention zapper on here, since the SUBCLASS is already a lightgun. This lead us to another part of the code that would go like this:

```
      case RETRO_DEVICE_ZAPPER:
         FCEUI_SetInput(port, SI_ZAPPER, nes_input.MouseData[port], 1);
         FCEU_printf(" Player %u: Zapper\n", port + 1);
         break;
      case RETRO_DEVICE_HWZAPPER:
         FCEUI_SetInput(port, SI_HWZAPPER, nes_input.LightgunData[port], 1);
         FCEU_printf(" Player %u: Zapper\n", port + 1);
         break;
```
The description here should be the same, this a terminal print that shouldn't be changed. I've made all this updates on my fork. Same for the options descriptions: `Invert Hardware Light Gun Trigger` should be `Invert Physical Zapepr Trigger` and so on...

Finally for device names on Input:

input.c / reference goes to extern: hwlightgun.c (I would call it hwzapper, but I've integrated it in the same zapper.c code)
```
extern INPUTC *FCEU_InitZapper(int w);
extern INPUTC *FCEU_InitHWLightgun(int w); // again here: FCEU_InitHWZapper
extern INPUTC *FCEU_InitMouse(int w);
extern INPUTC *FCEU_InitPowerpadA(int w); //look how Powerpad is divided in two defs, A and B. I think it's not implemented yet
extern INPUTC *FCEU_InitPowerpadB(int w);
```
libreto.c
```

static const struct retro_controller_description pads1[] = {
      { "Auto",               RETRO_DEVICE_AUTO },
      { "Gamepad",            RETRO_DEVICE_GAMEPAD },
      { "Zapper",             RETRO_DEVICE_ZAPPER },  //`Zapper (Emulated)` or just `Zapper` (for now)
      { "Hardware Light Gun", RETRO_DEVICE_HWLIGHTGUN }, // `Zapper (Physical)`. What do you think?
      { 0, 0 },
   };

   static const struct retro_controller_description pads2[] = {
      { "Auto",               RETRO_DEVICE_AUTO },
      { "Gamepad",            RETRO_DEVICE_GAMEPAD },
      { "Arkanoid",           RETRO_DEVICE_ARKANOID },
      { "Zapper",             RETRO_DEVICE_ZAPPER },
      { "Hardware Light Gun", RETRO_DEVICE_HWLIGHTGUN }, //Here too
```

Thanks @turley! please don't worry, as long as everyone here is happy, let's proceed, still, there are some important review changes I've placed. If there's stuff that has to be changed after this merge, I'll submit a new PR like you said. Thank you! 👍

2022-08-29 01:42 UTC, turley commented
@DigiDwrf Thanks - good points. Ultimately these are questions I think the project maintainers need to decide, so for now I'm going to avoid changing zapper stuff unless/until they clarify what they want to do.

2022-08-29 01:44 UTC, DigiDwrf commented
> @DigiDwrf Thanks - good points. Ultimately these are questions I think the project maintainers need to decide, so for now I'm going to avoid changing zapper stuff unless/until they clarify what they want to do.

Of course! 👍

2022-08-29 06:30 UTC, LibretroAdmin commented
Is this finally ready to go?

2022-08-29 09:37 UTC, DigiDwrf commented
> Is this finally ready to go?

@LibretroAdmin Not quite for me, but I can submit a new pull request after this merge. Some stuff has to be defined, since there's no device for the NES/FC refered as "Hardware Light Gun" in real life, this is just temporary until the existing mouse based `RETRO_DEVICE_ZAPPER` and the new lightgun based  `RETRO_DEVICE_HWLIGHTGUN` has propper names. I've used `RETRO_DEVICE_SWZAPPER` and `RETRO_DEVICE_HWZAPPER` in my fork, but could be any other names that could work better, e.g. `RETRO_DEVICE_M_ZAPPER` and `RETRO_DEVICE_L_ZAPPER`, this is something to be discussed, this naming concept affects many other definitions inside `libreto_core_options.h` and other files. I've submitted some reviews for @turley that still pending. If everybody else agree to merge at this point, I'm good to go.

2022-08-29 13:51 UTC, hizzlekizzle commented
I asked @negativeExponent to take a look and make sure it won't interfere with anything he's concerned with (VS arcade zapper games, etc.).

2022-08-29 15:13 UTC, LibretroAdmin commented
Let's not endlessly belabor this, though. Can somebody finish this up in a workable state by the enduser so we can merge this? Can we get this done before the end of the week? It doesn't have to be perfect on the first PR, improvements can follow later.

2022-08-29 18:57 UTC, hizzlekizzle commented
I talked to negativeExponent this morning and he expressed concern about future contributors being able to effectively differentiate between the software and hardware zappers internally in the code (i.e., not end users; the core options are pretty well covered with the sublabels, etc.) but he didn't have any specific objections. Just something to consider moving forward and when writing comments about the additions.

2022-08-29 19:15 UTC, turley commented
This is in a workable state. I just need to know if the maintainers are okay with the peripheral being called `Hardware Light Gun` (as it is in the PR currently), or if they want it changed to some variation of `Zapper`. If the former is ok for now (knowing that it may be renamed later), then it's ready to be merged.

I used `Hardware Light Gun` because it was suggested by @hizzlekizzle and is (in my opinion) easily distinguished from the existing `Zapper`. I'm happy to name it something else if the maintainers suggest something, but if it becomes a "zapper" of some kind, then it will probably require more extensive refactoring of the existing `zapper` to distinguish the two. I was hoping to avoid opening that can of worms, at least in this PR.

2022-08-29 19:18 UTC, hizzlekizzle commented
hardware light gun seems plenty explanatory to me

2022-08-29 20:00 UTC, DigiDwrf commented
> This is in a workable state. I just need to know if the maintainers are okay with the peripheral being called `Hardware Light Gun` (as it is in the PR currently), or if they want it changed to some variation of `Zapper`. If the former is ok for now (knowing that it may be renamed later), then it's ready to be merged.
> 
> I used `Hardware Light Gun` because it was suggested by @hizzlekizzle and is (in my opinion) easily distinguished from the existing `Zapper`. I'm happy to name it something else if the maintainers suggest something, but if it becomes a "zapper" of some kind, then it will probably require more extensive refactoring of the existing `zapper` to distinguish the two. I was hoping to avoid opening that can of worms, at least in this PR.

Sure! This will eventually evolve. The only thing I think is important to review right now is the end-user descripitons for devices (a.k.a. Gamepad, Zapper, Arkanoid, Mouse, Powerpad, etc.). At this point, @turley has stablished one device as `"Zapper"` (like it was before) and a new device called `"Hardware Light Gun"`. I think this will be the only issue for now, I think that `"Zapper (Physical)"` or something alike will work better on this first merge, at the end, we're talking about Zapper emulation through Libreto's existing Lightgun device. Despite all this matter, It's ok for me to go on @LibretroAdmin, since this code is already in a working state. Good job @turley I'm very gratefull for this 😄

2022-08-30 00:31 UTC, DigiDwrf requested changes
Opps didn´t know that I had to submit my reviews. No need to change them all, some I added days ago, so still optional, Just what we need for now, I'm requesting a new PR later on

2022-08-30 00:31 UTC, DigiDwrf commented on src/fceu.h
> +
let's be sure to line up that "0" with that "1" hehehe

2022-08-30 15:08 UTC, turley commented
I think we’ve moved beyond my level of experience and interest in this particular topic. I also don’t have time to contribute more to this discussion in a meaningful way.

@DigiDwrf - now that you’ve set up a proper fork (referencing the upstream repo), would you like to open a new pull request with your changes? If you want to do that, I’ll go ahead and close this one. Hopefully that will allow for a more complete implementation of this feature.

2022-08-30 20:32 UTC, DigiDwrf commented
> I think we’ve moved beyond my level of experience and interest in this particular topic. I also don’t have time to contribute more to this discussion in a meaningful way.
> 
> @DigiDwrf - now that you’ve set up a proper fork (referencing the upstream repo), would you like to open a new pull request with your changes? If you want to do that, I’ll go ahead and close this one. Hopefully that will allow for a more complete implementation of this feature.

I understand. Of course, I could request a new PR if you think is a better way to start with this merge.

@turley thanks again for bringing this topic, I'm kinda new in github so I really didn't know this was possible.

2022-08-30 20:52 UTC, turley commented
@DigiDwrf That sounds good. I was originally asked to submit this PR (which I thought was a pretty simple thing to add), and it was based on your code. At this point it makes the most sense for you to submit and finish it. You also seem to have a more complete idea for how the naming should be. Thanks.

2022-08-30 20:53 UTC, closed without merging

2024-07-04 17:21 UTC, riggles1 commented
I made a git detailing the build, new script with a couple of functions that makes it never miss in my extensive testing.
The setup is lagless so there's 1 single frame of delay coming from the emulation itself, so the delay is always set to 1.0 in the patched ROMs for everything to sync up.

A video showcasing the NES Zapper in action with libretro-fceumm's sequential targets mode:
https://i.imgur.com/D6HUQmy.mp4

Verified this on PC (Windows 10 64bit CRTEmudriver) and a Pi4 (RGBPi-Extras modified Pi4 image)

Everything from the wiring, script, rom patches to the crtemudriver setup is mentioned in my git: https://github.com/riggles1/Zapper-Arduino

2024-07-04 17:33 UTC, DigiDwrf commented
@riggles1 That's awesome. I fixed this funcionality and was merged to libreto:master long ago. You can even used unpatched roms configuring retroarch anticipated lag propperly, both core an emulator supports them.

2024-07-04 17:45 UTC, DigiDwrf commented
> I made a git detailing the build, new script with a couple of functions that makes it never miss in my extensive testing. The setup is lagless so there's 1 single frame of delay coming from the emulation itself, so the delay is always set to 1.0 in the patched ROMs for everything to sync up.
> 
> A video showcasing the NES Zapper in action with libretro-fceumm's sequential targets mode: https://i.imgur.com/D6HUQmy.mp4
> 
> Verified this on PC (Windows 10 64bit CRTEmudriver) and a Pi4 (RGBPi-Extras modified Pi4 image)
> 
> Everything from the wiring, script, rom patches to the crtemudriver setup is mentioned in my git: https://github.com/riggles1/Zapper-Arduino
> 
> With a photodiode swap mod the Zapper likely works with modern TVs as well, I'll likely be looking into that later on.

To make the zapper work with any tv, I swapped the phototransistor present on the zapper board with a transistor that is connected to an arduino board, and a phototransistor is connected to that arduino board this time, so any source of light is converted into a 15khz signal that triggers the IC present on the zapper board. You could say this is kinda strange, since it's easier just to send signal directly to the console from the arduino board, but I made it just for fun, and I wanted to keep using original board inside the zapper, and no lag whatsoever.